const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes.js');
const accountsRoutes = require('./accounts.routes.js');
const receiptsRoutes = require('./receipts.routes.js');
const categoriesRoutes = require('./categories.routes.js');
const exportsRoutes = require('./exports.routes.js');
const businessRoutes = require('./business.routes.js');
const systemRoutes = require('./system.routes.js');
const meRoutes = require('./me.routes.js');
const cryptoRoutes = require('./crypto.routes.js');
const privacyRoutes = require('./privacy.routes.js');
const mileageRoutes = require('./mileage.routes.js');
const sessionsRoutes = require('./sessions.routes.js');
const billingRoutes = require('./billing.routes.js');
const recurringRoutes = require('./recurring.routes.js');
const businessesRoutes = require('./businesses.routes.js');
const cpaAccessRoutes = require('./cpa-access.routes.js');
const cpaVerificationRoutes = require('./cpa-verification.routes.js');
const goalsRoutes = require('./goals.routes.js');
const analyticsRoutes = require('./analytics.routes.js');
const messagesRoutes = require('./messages.routes.js');

router.use('/auth', authRoutes);
router.use('/accounts', accountsRoutes);
router.use('/receipts', receiptsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/exports', exportsRoutes);
router.use('/business', businessRoutes);
router.use('/system', systemRoutes);
router.use('/', systemRoutes);
router.use('/me', meRoutes);
router.use('/crypto', cryptoRoutes);
router.use('/privacy', privacyRoutes);
router.use('/mileage', mileageRoutes);
router.use('/sessions', sessionsRoutes);
router.use('/billing', billingRoutes);
router.use('/recurring', recurringRoutes);
router.use('/businesses', businessesRoutes);
router.use('/cpa-access', cpaAccessRoutes);
router.use('/cpa-verification', cpaVerificationRoutes);
router.use('/goals', goalsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/messages', messagesRoutes);

module.exports = router;
