const WORKER_BASE_URL = (process.env.PDF_WORKER_URL || "").replace(/\/+$/, "");
const WORKER_SECRET = process.env.PDF_WORKER_SECRET;
const WORKER_TIMEOUT_MS = Number(process.env.PDF_WORKER_TIMEOUT_MS || 15_000);

function createPdfPlaceholder(job, includeTaxId) {
  const header = `Export Job ${job.jobId}\n`;
  const metadata = [
    `Business: ${job.businessId}`,
    `User: ${job.userId}`,
    `Date range: ${job.startDate} -> ${job.endDate}`,
    `Include tax ID: ${includeTaxId}`
  ];

  const body = [
    header,
    ...metadata.map((line) => `• ${line}`),
    "",
    "This PDF is a simulated payload generated by the pdf-worker client.",
    "Full delivery is streamed; redacted history only stores masked content."
  ].join("\n");

  return Buffer.from(body, "utf-8");
}

function buildPlaceholderResponse(job) {
  const includeTaxId = Boolean(job.includeTaxId);
  return {
    fullPdfBuffer: createPdfPlaceholder(job, includeTaxId),
    redactedPdfBuffer: createPdfPlaceholder({ ...job, includeTaxId: false }, false),
    metadata: {
      pageCount: 1,
      notes: "Simulated pdf-worker output; replace with TEE pipeline."
    }
  };
}

async function callWorker(job) {
  if (!WORKER_BASE_URL || !WORKER_SECRET) {
    throw new Error("PDF worker configuration is missing");
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), WORKER_TIMEOUT_MS);

  try {
    const response = await fetch(`${WORKER_BASE_URL}/generate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Worker-Token": WORKER_SECRET
      },
      body: JSON.stringify(job),
      signal: controller.signal
    });

    if (!response.ok) {
      const body = await response.text().catch(() => "");
      throw new Error(`Worker error ${response.status}: ${body}`);
    }

    const payload = await response.json();
    return {
      fullPdfBuffer: Buffer.from(payload.fullPdf, "base64"),
      redactedPdfBuffer: Buffer.from(payload.redactedPdf, "base64"),
      metadata: payload.metadata || {}
    };
  } finally {
    clearTimeout(timeout);
  }
}

export async function dispatchPdfJob(job) {
  if (WORKER_BASE_URL && WORKER_SECRET) {
    try {
      return await callWorker(job);
    } catch (err) {
      console.error("PDF worker dispatch failed:", err.message);
      throw err;
    }
  }

  return buildPlaceholderResponse(job);
}


