import crypto from "node:crypto";

function createPdfPlaceholder(job, includeTaxId) {
  const header = `Export Job ${job.jobId}\n`;
  const metadata = [
    `Business: ${job.businessId}`,
    `User: ${job.userId}`,
    `Date range: ${job.startDate} -> ${job.endDate}`,
    `Include tax ID: ${includeTaxId}`
  ];

  const body = [
    header,
    ...metadata.map((line) => `• ${line}`),
    "",
    "This PDF is a simulated payload generated by the pdf-worker client.",
    "Full delivery is streamed; redacted history only stores masked content."
  ].join("\\n");

  return Buffer.from(body, "utf-8");
}

export async function dispatchPdfJob(job) {
  const includeTaxId = Boolean(job.includeTaxId);
  const fullPdfBuffer = createPdfPlaceholder(job, includeTaxId);
  const redactedPdfBuffer = createPdfPlaceholder({ ...job, includeTaxId: false }, false);

  return {
    fullPdfBuffer,
    redactedPdfBuffer,
    metadata: {
      pageCount: 1,
      notes: "Simulated pdf-worker output; replace with TEE pipeline."
    }
  };
}
