import express from "express";
import dotenv from "dotenv";
import ipaddr from "ipaddr.js";
import { importJWK, compactDecrypt } from "jose";
import { logInfo, logError } from "./logger.js";

dotenv.config();

const PORT = Number(process.env.PORT || 9080);
const WORKER_SECRET = process.env.PDF_WORKER_SECRET;
const PRIVATE_KEY_JWK = process.env.PDF_WORKER_PRIVATE_KEY_JWK;
const ALLOWED_CIDRS = (process.env.PDF_WORKER_ALLOWED_CIDRS || "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16")
  .split(",")
  .map((cidr) => cidr.trim())
  .filter(Boolean);

if (ALLOWED_CIDRS.length === 0) {
  throw new Error("PDF_WORKER_ALLOWED_CIDRS must include at least one CIDR range.");
}

const parsedCidrs = ALLOWED_CIDRS.map((cidr) => {
  try {
    return ipaddr.parseCIDR(cidr);
  } catch (err) {
    throw new Error(`Invalid CIDR in PDF_WORKER_ALLOWED_CIDRS: ${cidr}`);
  }
});

function getRemoteIp(req) {
  const forwarded = req.headers["x-forwarded-for"];
  if (forwarded) {
    return forwarded.split(",")[0].trim();
  }
  return req.socket.remoteAddress || "";
}

function isIpAllowed(ipValue) {
  if (!ipValue) return false;
  let parsed;
  try {
    parsed = ipaddr.parse(ipValue);
  } catch {
    return false;
  }
  return parsedCidrs.some(([network, prefix]) => parsed.kind() === network.kind() && parsed.match(network, prefix));
}

if (!WORKER_SECRET) {
  throw new Error("Missing PDF_WORKER_SECRET (shared secret for API traffic).");
}

if (!PRIVATE_KEY_JWK) {
  throw new Error("Missing PDF_WORKER_PRIVATE_KEY_JWK (attested RSA key material).");
}

let cachedPrivateKey = null;

async function getPrivateKey() {
  if (cachedPrivateKey) {
    return cachedPrivateKey;
  }
  const parsed = JSON.parse(PRIVATE_KEY_JWK);
  cachedPrivateKey = await importJWK(parsed, "RSA-OAEP-256");
  return cachedPrivateKey;
}

async function decryptTaxId(jwe) {
  if (!jwe) return null;
  const key = await getPrivateKey();
  const { plaintext } = await compactDecrypt(jwe, key);
  return new TextDecoder().decode(plaintext);
}

function encodeBase64(buffer) {
  return Buffer.from(buffer).toString("base64");
}

function buildPdfContent(job, taxId, redact = false) {
  const divider = "─".repeat(60);
  const thin = "·".repeat(60);

  const businessName = job.businessName ? String(job.businessName).trim() : "InEx Ledger";
  const exportLabel = `Export Report — ${businessName}`;
  const jobLine = `Job ID : ${job.jobId || "unknown"}`;
  const rangeLine = `Period : ${job.startDate || "N/A"} to ${job.endDate || "N/A"}`;
  const langLine = `Language : ${job.exportLang || "en"}`;
  const currencyLine = `Currency : ${job.currency || "USD"}`;
  const taxLine = redact
    ? "Tax ID  : [REDACTED]"
    : `Tax ID  : ${taxId ? taxId : "Not provided"}`;
  const generatedLine = `Generated: ${new Date().toISOString()}`;

  const transactions = Array.isArray(job.transactions) ? job.transactions : [];

  let txSection = "";
  if (transactions.length > 0) {
    const rows = transactions.map((tx) => {
      const date = String(tx.date || "").padEnd(12);
      const type = String(tx.type || "").padEnd(10);
      const amount = String(tx.amount != null ? tx.amount : "").padStart(12);
      const desc = String(tx.description || "").substring(0, 30);
      return `  ${date}  ${type}  ${amount}  ${desc}`;
    });
    txSection = [
      "",
      divider,
      "  TRANSACTIONS",
      divider,
      "  Date          Type        Amount        Description",
      thin,
      ...rows,
      thin,
      `  Total entries: ${transactions.length}`
    ].join("\n");
  } else {
    txSection = [
      "",
      divider,
      "  TRANSACTIONS",
      divider,
      "  (No transactions in the selected date range.)"
    ].join("\n");
  }

  const header = [
    divider,
    `  ${exportLabel}`,
    divider,
    `  ${jobLine}`,
    `  ${rangeLine}`,
    `  ${langLine}`,
    `  ${currencyLine}`,
    `  ${taxLine}`,
    thin,
    `  ${generatedLine}`
  ].join("\n");

  const footer = [
    "",
    divider,
    "  This document was generated by InEx Ledger.",
    "  Keep a copy for your tax records.",
    divider
  ].join("\n");

  return Buffer.from(`${header}${txSection}${footer}\n`, "utf-8");
}

const app = express();
app.use(express.json({ limit: "1mb" }));

app.get("/health", (_req, res) => {
  res.json({ status: "ok" });
});

app.use((req, res, next) => {
  const remoteIp = getRemoteIp(req);
  if (!isIpAllowed(remoteIp)) {
    logError("Blocked worker request from unauthorized IP", new Error("Unauthorized IP"), {
      path: req.path,
      ip: remoteIp
    });
    return res.status(403).json({ error: "Access denied" });
  }
  next();
});

app.use((req, res, next) => {
  const token = req.headers["x-worker-token"];
  if (token !== WORKER_SECRET) {
    logError("Unauthorized worker request", new Error("Invalid token"), { path: req.path });
    return res.status(401).json({ error: "Unauthorized" });
  }
  next();
});

app.post("/generate", async (req, res) => {
  const job = req.body || {};
  const includeTaxId = Boolean(job.includeTaxId);
  try {
    const taxId = includeTaxId ? await decryptTaxId(job.taxId_jwe) : null;
    const fullPdfBuffer = buildPdfContent(job, taxId, false);
    const redactedPdfBuffer = buildPdfContent(job, taxId, true);

    logInfo("Worker generated PDFs", { jobId: job.jobId, includeTaxId });

    res.json({
      jobId: job.jobId,
      fullPdf: encodeBase64(fullPdfBuffer),
      redactedPdf: encodeBase64(redactedPdfBuffer),
      metadata: {
        language: job.exportLang || "en",
        currency: job.currency || "USD",
        pageCount: 2,
        taxIdIncluded: includeTaxId && Boolean(taxId)
      }
    });
  } catch (err) {
    logError("Worker failed", err, { jobId: job.jobId });
    res.status(500).json({ error: "Failed to generate PDF." });
  }
});

app.listen(PORT, () => {
  logInfo("Worker ready", { port: PORT });
});
